"""empty message

Revision ID: 2d1802fe5671
Revises: 429b926db31
Create Date: 2016-01-31 16:02:47.767046

"""

# revision identifiers, used by Alembic.
revision = '2d1802fe5671'
down_revision = '429b926db31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
